version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - db
    command:
      sleep infinity

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --storage-driver vfs
